### ISSUE TITLE
Implement the gloo interface on top of the GLIR JavaScript implementation

### ISSUE THREAD

**Issue by rossant** [vispy/vispy.js#1]

**Comment by almarklein** [comment]
I think it should be the other way around; we need a gloo-like library that interacts directly with GL (no lazy execution of commands), and then the glir interpreter should be a thin layer on top of that.

Other than in Python, lazy evaluation is not necessary, since the the canvas already exists. 

I've now been using the glir API from vispy.js to bring webgl support to Bokeh, but I feel I need something simpler. I don't to pass commands as strings so much, and since I'm in Bokeh's event loop (not vispy's) I find myself calling `glx.execute_pending_commands()`. 

I'll probably have a stab at this today.

**Comment by rossant** [comment]
@almarklein it sounds like a good approach

did you have time to try it yet?

**Comment by almarklein** [comment]
Yes, I have something, but it's limited to the functionality that I need right now. I might have a chance to make a PR next week or so.

**Comment by djhoese** [comment]
The VisPy Python library now depends on a new `jupyter_rfb` backend (to be released in 0.8.0, not out yet). As such, we have deprecated and removed the `ipynb_webgl` backend. This means the `vispy.js` project will not be used by the VisPy project anymore and will not receive active development. I'm closing this issue because of this and will be archiving the repository making it read-only.
