### ISSUE TITLE
Share GL context in the browser

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy.js#16]
Most browsers limit the number of WebGL contexts on one page to 16. Using more will kill the oldest context, killing the visualization. This is problematic, because 16 plots is not an uncommon number of plots for an IPython notebook. 

Further, it would be nice to be able to share contexts for e.g. linked plots. However, WebGL does not allow sharing contexts ...

But there is a trick in which can fix both of the above problems :)

The trick is that for each plot/canvas you create a DOM canvas element with a `2d` rendering context, and you create a single invisible canvas element with a `webgl` context. When drawing to plot/canvas A, you first make the invisible canvas the same size, then do the rendering, and finally you blit the result into the 2D canvas using `drawImage`. For plot/canvas B you do the same.

The crucial bit is here (which might not be obvious at first) is that blitting the gl canvas into the 2d canvas is _very_ fast. There is no call to `glReadPixels` (which is a notoriously slow API call). Apparently, this bitting occurs on the GPU. Interestingly, it is even faster than rendering a 2D canvas into a gl canvas. We use this blitting technique in Bokeh to combine gl-drawn and 2d-drawn content, but I recently realized it is more generally applicable.

**Comment by larsoner** [comment]
Sounds good to me

**Comment by djhoese** [comment]
The VisPy Python library now depends on a new `jupyter_rfb` backend (to be released in 0.8.0, not out yet). As such, we have deprecated and removed the `ipynb_webgl` backend. This means the `vispy.js` project will not be used by the VisPy project anymore and will not receive active development. I'm closing this issue because of this and will be archiving the repository making it read-only.
